version: '3.8'

services:
  cliente-persona:
    image: cliente-persona-microservice
    container_name: cliente-persona
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  
  cuenta-movimientos:
    image: cuenta-movimientos-microservice
    container_name: cuenta-movimientos
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: microservicios_db
      MYSQL_PASSWORD: sasa
    ports:
      - "3307:3307"
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"