version: '3.8'

services:
  cliente-persona:
    image: cliente-persona-microservice
    container_name: cliente-persona
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservicios-network
  
  cuenta-movimientos:
    image: cuenta-movimientos-microservice
    container_name: cuenta-movimientos
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    networks:
      - microservicios-network  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: microservicios_db
      MYSQL_PASSWORD: sasa
    ports:
      - "3307:3307"
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  microservicios-network:
    driver: bridge